# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39a507a9159f95d57b2b652f6d9d7ef266f16a8532be6368367a14527866c8db104700ef7aac1c670d3bd335c2be95c0260e2ab08c6750e09274bf34c3680f2e

test:
  secret_key_base: af99e062521e7da3cdd23b1e954d20bcd2a3c6e078a4015b900d63af95c277bb7fe44af3b6a51b24cadd35cf5dff40250673ef8b7b097bd418d638a3407132c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
